# Generated by Django 3.1.4 on 2020-12-27 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_users_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='password',
        ),
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
    ]
