# Generated by Django 3.1.4 on 2020-12-27 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201227_2202'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
