# Generated by Django 3.1.4 on 2020-12-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voitings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('about', models.CharField(max_length=1000)),
            ],
        ),
    ]
