# Generated by Django 3.1.4 on 2020-12-27 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_voitings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Voitings',
            new_name='Votings',
        ),
    ]
