# Generated by Django 3.1.4 on 2020-12-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201227_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='votings',
            name='all_votes_quantity',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votings',
            name='author',
            field=models.CharField(default=100, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='votings',
            name='name',
            field=models.TextField(),
        ),
    ]
