# Generated by Django 3.1.4 on 2020-12-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201229_1406'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AddField(
            model_name='votings',
            name='variants',
            field=models.TextField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votings',
            name='variants_values',
            field=models.TextField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='votings',
            name='about',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='votings',
            name='author',
            field=models.TextField(),
        ),
    ]
