# Generated by Django 3.1.4 on 2020-12-29 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
