# Generated by Django 3.1.5 on 2021-01-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='history',
            field=models.TextField(),
        ),
    ]
