# Generated by Django 3.1.5 on 2021-01-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_complaintshistoty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votings',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
