# Generated by Django 3.1.5 on 2021-01-30 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210130_0030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComplaintsHistoty',
            new_name='Complaints',
        ),
    ]
