# Generated by Django 3.1.5 on 2021-01-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210131_0203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaints',
            old_name='complaintfirst',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='complaints',
            name='author',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaints',
            name='message',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
