# Generated by Django 3.1.5 on 2021-01-30 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210131_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='user_id',
            field=models.IntegerField(default=None),
        ),
    ]
