# Generated by Django 3.1.5 on 2021-01-31 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20210131_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='votings',
            name='participants',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
